### PR TITLE
Handle parentheses in authorship matching

### PR DESCRIPTION
**Pull request by LordFlashmeow**
`cached_author` doesn't have parentheses, so they must be stripped from verbatim field before searching.

### CODE REVIEW

**Comment by LocoDelAssembly** [comment]
@LordFlashmeow two things:
1) I searched on DB and found this:
```ruby
irb(main):001:0> TaxonName.where("cached_author LIKE '%(%'").count
=> 29760
```
Not sure if this is what you mean by cached author not having parens? On the other hand, count looks somewhat low. Could this be bad data @mjy @proceps?

2) Would you fix merge conflict please?

**Comment by LordFlashmeow** [comment]
> I think `cached_author` _can_ have parens, but remember it doesn't have year inside it. This may be where the missmatch is?
What's the source of truth for this? 

The comments in the file say that it shouldn't have parentheses, and the `set_cached_author` method appears to strip parentheses from `cached_author_year`.

https://github.com/SpeciesFileGroup/taxonworks/blob/7d4757e8f868e600c1b377eb5aa7230499d13531/app/models/taxon_name.rb#L88-L90

https://github.com/SpeciesFileGroup/taxonworks/blob/7d4757e8f868e600c1b377eb5aa7230499d13531/app/models/taxon_name.rb#L1122-L1124

https://github.com/SpeciesFileGroup/taxonworks/blob/7d4757e8f868e600c1b377eb5aa7230499d13531/app/models/taxon_name.rb#L689-L693

**Comment by proceps** [comment]
`cached_author_year` may have parentheses; `cached_author` should not. Looking at the code.

**Comment by proceps** [comment]
`cached_author` was not updated properly when year was not present. The problem with botanical names, which often contain parentheses.

**Comment by LocoDelAssembly** [comment]
The fix applied in https://github.com/SpeciesFileGroup/taxonworks/commit/b123bf08abaffed7a064723c1ad695ed63b9082d is going to remove trailing paren as it wasn't doing it before. However we have many instances that leading paren is also present and happens in both ICZN and ICN.

Dropping some debug data here:
```ruby
ap %w{(% %(% %) %)%}.map { |x| [ x, TaxonName.where("cached_author LIKE '#{x}'").group(:rank_class).count] }.to_h
{
     "(%" => {                                                                                                                                                               
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => 11,                                                                                             
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => 4,                                                                                              
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => 1792,                                                                                           
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => 86,                                                                                             
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => 53,                                                                                             
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => 21750,                                                                                          
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => 2207,                                                                                           
                                                                      nil => 3846                                                                                            
    },                                                                                                                                                                       
    "%(%" => {                                                                                                                                                               
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => 11,                                                                                             
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => 4,                                                                                              
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => 1799,                                                                                           
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => 86,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => 53,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => 21751,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => 2207,
                                                                      nil => 3846
    },
     "%)" => {
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => 162,
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => 1,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => 1,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => 14066,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => 1157,
                                                                      nil => 235
    },
    "%)%" => {
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => 11,
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => 4,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => 1799,
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => 86,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => 53,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => 14184,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => 1158,
                                                                      nil => 235
    }
}

```
```ruby
ap %w{(% %(% %) %)%}.map { |x| [ x, TaxonName.where("cached_author LIKE '#{x}'").group(:rank_class).maximum(:created_at)] }.to_h
{
     "(%" => {                                                                                                                                                               
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => Fri, 20 Oct 2023 17:39:57.138392000 UTC +00:00,                                                 
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => Fri, 23 Jun 2023 18:48:58.148607000 UTC +00:00,                                                 
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => Mon, 04 Dec 2023 18:02:04.711107000 UTC +00:00,                                                 
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => Fri, 01 Dec 2023 20:06:15.411184000 UTC +00:00,                                                 
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => Wed, 08 Nov 2023 14:51:17.759579000 UTC +00:00,                                                 
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => Tue, 21 Nov 2023 17:04:17.111806000 UTC +00:00,                                                 
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => Mon, 06 Nov 2023 12:26:55.958533000 UTC +00:00,                                                 
                                                                      nil => Thu, 23 Nov 2023 07:22:37.285267000 UTC +00:00                                                  
    },                                                                                                                                                                       
    "%(%" => {                                                                                                                                                               
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => Fri, 20 Oct 2023 17:39:57.138392000 UTC +00:00,                                                 
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => Fri, 23 Jun 2023 18:48:58.148607000 UTC +00:00,                                                 
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => Mon, 04 Dec 2023 18:02:04.711107000 UTC +00:00,                                                 
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => Fri, 01 Dec 2023 20:06:15.411184000 UTC +00:00,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => Wed, 08 Nov 2023 14:51:17.759579000 UTC +00:00,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => Tue, 21 Nov 2023 17:04:17.111806000 UTC +00:00,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => Mon, 06 Nov 2023 12:26:55.958533000 UTC +00:00,
                                                                      nil => Thu, 23 Nov 2023 07:22:37.285267000 UTC +00:00
    },
     "%)" => {
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => Tue, 01 Oct 2019 12:16:43.617542000 UTC +00:00,
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => Tue, 28 Aug 2012 17:07:05.000000000 UTC +00:00,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => Tue, 28 Aug 2012 17:07:05.000000000 UTC +00:00,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => Tue, 21 Nov 2023 17:04:17.111806000 UTC +00:00,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => Mon, 06 Nov 2023 12:26:55.958533000 UTC +00:00,
                                                                      nil => Thu, 23 Nov 2023 07:22:37.285267000 UTC +00:00
    },
    "%)%" => {
                              "NomenclaturalRank::Icn::GenusGroup::Genus" => Fri, 20 Oct 2023 17:39:57.138392000 UTC +00:00,
              "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Form" => Fri, 23 Jun 2023 18:48:58.148607000 UTC +00:00,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Species" => Mon, 04 Dec 2023 18:02:04.711107000 UTC +00:00,
        "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Subspecies" => Fri, 01 Dec 2023 20:06:15.411184000 UTC +00:00,
           "NomenclaturalRank::Icn::SpeciesAndInfraspeciesGroup::Variety" => Wed, 08 Nov 2023 14:51:17.759579000 UTC +00:00,
                         "NomenclaturalRank::Iczn::SpeciesGroup::Species" => Tue, 21 Nov 2023 17:04:17.111806000 UTC +00:00,
                      "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies" => Mon, 06 Nov 2023 12:26:55.958533000 UTC +00:00,
                                                                      nil => Thu, 23 Nov 2023 07:22:37.285267000 UTC +00:00
    }
}
```

Do ICZN need `cached_author` refreshed if there are parens? Have been other changes besides above mentioned commit? ICZN names with parens in cached_author have a fairly recent maximum `created_at`, but not as recent as ICN ones.

**Comment by mjy** [comment]
Ping @proceps ^

**Comment by mjy** [comment]
Potentially - see my comments on `TaxonName.get_author`.  We still have some jankyness left over from pre-`cached_author` implementation.  In other words `get_author` is should not be necessary.

**Comment by proceps** [comment]
plant names have parentheses. If there are problems with ICZN names, I need an example.

**Comment by mjy** [comment]
`cached_author` is *without* parens (see the definition).  The point of it is to capture name strings that can be presented as name strings/agent strings.  I see many parens there.  Parens should only exist in `cached_author_year`.  So if we are putting parens in there for any reason we've got model confusion.

**Comment by proceps** [comment]
There was a bug in the model, which should be fixed now. What do we do with plant names: '(John) Smith'. I am not sure how those should be preserved. We need an advise from ICN community.

**Comment by mjy** [comment]
That's not the point, the column is for people's name, sortable, findable.  It is code agnostic.  To render in cotext of code we use cached_author_year, like we have always done pre cached_author.

**Comment by mjy** [comment]
We render paranes for plant names by a) including them in verbatim_author, or b) creating rules that act one People.

**Pull request merged**
