### PR TITLE
In otuPicker don't try to assign taxon.id to a new otu when no taxon …

### PR DESCRIPTION
**Pull request by kleintom**
…is selected

Followup on #3809

### CODE REVIEW

**Comment by kleintom** [comment]
Maybe this should be a new issue (if so, feel free to ask me to file it), but I figure you're probably already aware - mentioning it just in case: I noticed that when you select or create an otu with no name using the otu picker, there's nothing displayed for the otu:
image
Would it make sense to display the taxon name or something else in that case?

**Comment by jlpereira** [comment]
> Maybe this should be a new issue (if so, feel free to ask me to file it), but I figure you're probably already aware - mentioning it just in case: I noticed that when you select or create an otu with no name using the otu picker, there's nothing displayed for the otu: image Would it make sense to display the taxon name or something else in that case?

Context? What is the task? `object_label` or `object_tag` should contain the taxon name

**Comment by kleintom** [comment]
Sorry, two separate issues, I think both apply anywhere the otu picker appears, for example in the Simple New Specimen task.
* The patch is for the case where you enter an unrecognized name in the otu picker and it offers to create a new otu for you, and you click Create without entering a taxon name:
image
In that case `taxon` is undefined and you get an exception.

* My other comment is just a UI question concerning the taxon name being blank - not that you're missing an object that holds the taxon name, just that that name is undefined, which means the picker displays blank, so there's no way to tell which otu you chose by looking at the UI, as in the image in my previous comment.  You can get a legitimate blank name from the picker in a couple ways:
  * if you enter the taxon of an otu that has a taxon but a blank name, for example an otu that was auto-created when you clicked on the no-associated-otu soft-validation fix on a new taxon name that didn't yet have an associated otu; or
  * if you enter the name of a taxon that matches no existing otus and the picker offers to create an otu for you via the 'Create and use OTU for taxon name ...' option:
 
image

**Comment by jlpereira** [comment]
@kleintom I think I found the interface where you see this, Simple new specimen, right? The problem is not related with Otu picker. I pushed a fix for it, let me know if that works.

**Comment by kleintom** [comment]
Yup, that fixed the blank name issue, thanks!

**Pull request merged**
