### PR TITLE
3867 adds sic handling to Protonym#original_combination_infraspecific_element

### LINKED ISSUE #3867: [Bug]: For misspelled infraspecies the Protonym.original_combination_infraspecific_element method returns [sic]
### Steps to reproduce the bug

```bash
When calling the original_combination_infraspecific_element method from the Protonym model, it returns ["subspecies", "[sic]"] if the original combination includes [sic] like "Anacanthaspis bifasciata japanica [sic]".



(byebug) ap t
#<Protonym:0x00007f995a80ae80> {
                                               :id => 4927974,
                                             :name => "japanica",
                                        :parent_id => 4817316,
                                      :cached_html => "<i>Anacanthaspis japanica</i> [sic]",
                               :cached_author_year => "Shiraki, 1932",
                                       :created_at => Wed, 16 Nov 2005 00:00:00.000000000 UTC +00:00,
                                       :updated_at => Tue, 20 Jun 2023 00:00:00.000000000 UTC +00:00,
                              :year_of_publication => nil,
                                  :verbatim_author => nil,
                                       :rank_class => NomenclaturalRank::Iczn::SpeciesGroup::Species < NomenclaturalRank::Iczn::SpeciesGroup,
                                             :type => "Protonym",
                                    :created_by_id => 546,
                                    :updated_by_id => 546,
                                       :project_id => 78,
                 :cached_original_combination_html => "<i>Anacanthaspis bifasciata japanica</i> [sic]",
                         :cached_secondary_homonym => "Anacanthaspis japanica",
                           :cached_primary_homonym => "Anacanthaspis japanica",
    :cached_secondary_homonym_alternative_spelling => "Anacanthaspis iapanica",
      :cached_primary_homonym_alternative_spelling => "Anacanthaspis iapanica",
                               :cached_misspelling => true,
                                   :masculine_name => nil,
                                    :feminine_name => nil,
                                      :neuter_name => nil,
                             :cached_classified_as => nil,
                                           :cached => "Anacanthaspis japanica [sic]",
                                    :verbatim_name => nil,
                       :cached_valid_taxon_name_id => 4817318,
                                        :etymology => nil,
                      :cached_original_combination => "Anacanthaspis bifasciata japanica [sic]",
                         :cached_nomenclature_date => 1932-12-31,
                                  :cached_is_valid => false,
                                    :cached_author => "Shiraki"
}
nil
(byebug) t.original_combination_infraspecific_element
["subspecies", "[sic]"]

(byebug) t.original_combination_elements
{:genus=>[nil, "Anacanthaspis"], :species=>[nil, "bifasciata"], :subspecies=>[nil, "japanica", "[sic]"]}
```
```


### Screenshot

_No response_

### Expected behavior

I'd expect it to return: 

["subspecies", "japanica"]


### Additional Screenshots

_No response_

### Environment

Development (native)

### Sandbox Used

_No response_

### Version

_No response_

### Browser Used

_No response_

### PR DESCRIPTION
**Pull request by gdower**
This fixes #3867, although I could also potentially keep the sic handling in the COLDP exporter instead of the model, depending on whether Protonym#original_combination_infraspecific_element and Protonym#original_combination_elements are supposed to include [sic] elements?

### CODE REVIEW

**Comment by gdower** [comment]
According to @proceps those methods are supposed to include [sic] elements so I'll move the [sic] handling into the COLDP exporter instead.

**Comment by mjy** [comment]
> According to @proceps those methods are supposed to include [sic] elements so I'll move the [sic] handling into the COLDP exporter instead

Yes, this is the way.

**Comment by mjy** [comment]
@gdower don't close this quite yet, need to reflect further now that I better understand the actual code.

**Comment by mjy** [comment]
Since this is an option usable for CoL without impacting "core" use I've merged it.

**Pull request merged**
