### PR TITLE
Key hub improvements

### PR DESCRIPTION
**Pull request by kleintom**
Here's a screenshot of how it looks now:
image

Otus and citations for a key are listed below that key's row in the keys table. The root otu and the root citations of each key are loaded right away; there's a button to load any other otus from a given key - in the screenshot that button has been clicked on the second and third keys already.

Like I said earlier, thoughts on both the ui and the ux welcome, and I don't have any expectations that this will make it into the current release but if you want to cherry-pick anything here feel free.

### CODE REVIEW

**Comment by mjy** [comment]
@kleintom I like the concepts.  Some observations: 

* [ ] Do we need radial annotators beside each citation?  The should be redundant with the in-line rightmost annotator if they are referencing leads.
* [ ] Let's not use underline here as we don't have this pattern elsewhere and in general underline suggests a link (we use blue text for links).
* [ ] Perhaps you could add a row with 2 spanning columns, one for the OTUs, and one for the citaitons, this might make the table feel a little more cohesive (nitpicking here)
* [ ] Hyperlink the text (title) of the key to goto the browse/show task

**Comment by kleintom** [comment]
> * Do we need radial annotators beside each citation?

They're citation annotators, but I don't have a feel for how useful that actually is, I'll remove them.

**Comment by kleintom** [comment]
> * (nitpicking here)

Nitpicks welcome, here's a new screenshot, see what you think:
image

**Comment by mjy** [comment]
@kleintom merging this as is to sneak it in, you can PR against development again please.

**Pull request merged**
