### PR TITLE
Instructions for importing a data download in a Docker Compose dev env

### PR DESCRIPTION
**Pull request by neolefty**
Documentation only.

* Are these instructions correct?
    * They are tested, but is there a better way?
* Is this a good (or only) place to put the documentation?

### CODE REVIEW

**Comment by LocoDelAssembly** [comment]
`docker compose exec db psql -U postgres -d taxonworks_development -f /mnt/unzip/dump.sql`

I believe you can just send through stdin and save yourself from adding another volume:

`docker compose exec db psql -U postgres -d taxonworks_development -f - < local/path/dump.sql`

[https://github.com/SpeciesFileGroup/install_taxonworks/tree/master/development/docker#restore-a-database-dump](Here) there is an example with `pg_restore` (doesn't work with `sql` files)

**Comment by neolefty** [comment]
> `docker compose exec db psql -U postgres -d taxonworks_development -f /mnt/unzip/dump.sql`
> 
> I believe you can just send through stdin and save yourself from adding another volume:
> 
> `docker compose exec db psql -U postgres -d taxonworks_development -f - < local/path/dump.sql`
> 
> [https://github.com/SpeciesFileGroup/install_taxonworks/tree/master/development/docker#restore-a-database-dump](Here) there is an example with `pg_restore` (doesn't work with `sql` files)

Thanks for the suggestion — that would be better.

However, I tried that but didn't get it to work:

```shell
$ echo "select count(id) from users;" > foo.sql
$ docker compose exec db psql -U postgres -d taxonworks_development -f - < foo.sql
WARN[0000] /Users/wbbaker/source/taxonworks/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
the input device is not a TTY
```

**Comment by LocoDelAssembly** [comment]
As discussed in https://github.com/SpeciesFileGroup/taxonworks_doc/pull/94#issuecomment-2512331198 perhaps such warning should also appear here. Text might become too big already and perhaps we should consider linking to docs for ways on restoring dumps instead of keep expanding.

Other than that, the instructions in this PR are correct. Perhaps we can merge, then refactor to link to docs with more use cases and extended explanation.

**Comment by mjy** [comment]
> Perhaps we can merge, then refactor to link to docs with more use cases and extended explanation.

Agreed.  We'll merge this *after* 0.46.0 release. 

We need some cannonical way to store linkages between app and documentation endpoints, maybe a config file that lets us introduce help tags pointing to help keywords, perhaps something likeK

```yml
# config/initializers/help_index.yml
---
help_keyword: 
  url: 
keyword_keyword2: 
  url:
```

`<%= help_link(help_keyword) %>`

or 

`/help/:keyword` to get the JSON response to inject the link.

**Pull request merged**
