### PR TITLE
Add Redis support

### PR DESCRIPTION
**Pull request by LocoDelAssembly**
Wait for test

### CODE REVIEW

**Comment by LocoDelAssembly** [comment]
@mjy this implements https://github.com/SpeciesFileGroup/taxonworks/issues/1082#event-2677640630 . However please don't close the issue yet, have to revise, we should probably be using the customizable image instead of ruby25. The test failed but because it merged against a broken commit. Works fine locally:
```terminal
Docker image test
  dashboard page
    shows that the dashboard is for the logged in user
    shows the revision matching git HEAD short hash (45eedb6)
  HTTP proxy
    has not recorded any error response


===URLs served===
Status	URL
200	http://ocsp.digicert.com/
200	http://ocsp.digicert.com/
200	http://ocsp.digicert.com/
301	http://taxonworks/
200	http://ocsp.digicert.com/
200	http://taxonworks/signin
200	http://taxonworks/assets/application-6d8dc4ef8295a036245651ac92d4ec32316762f1bb0da8fb8902194aebe4b159.css
200	http://taxonworks/favicon.ico
200	http://taxonworks/assets/taxonworks_logo-full-b24d1de4ca69518588720e4f31a117d520503efb4303fd92568ff420eac6fb82.svg
302	http://taxonworks/sessions
200	http://taxonworks/
200	http://taxonworks/assets/application-2ccf72662fe4a8e4ccddaf6f907932d97a36348e461f1e996e8b074af2b0aa8e.js
200	http://taxonworks/assets/separated_application-cceff7cc95a7fe7a32ce8df2058a609c74534c2dad2fd05fab82e34ea070b75a.js
200	http://taxonworks/packs/js/application-014967604f81d0ed6f6f.js
200	http://taxonworks/packs/css/application-09f47d4c.css
200	http://taxonworks/assets/taxonworks-white-428e02ed1e5d91384355501aa6a8f8d827ca68a18c1c7c72483c16f1284fbfad.svg
200	http://taxonworks/assets/taxonworks-black-circle-4b3430a9537c1dee58f566090950ac632472f88e7b6029180b7b6fd70748ad04.svg
200	http://taxonworks/assets/folders-d4e4d09045ad3e2f6900ee1408935a1f11e292cc436c2b1386bf45f80f9fdee1.svg
200	http://taxonworks/assets/open_folder-98b827a9ca6fdfdf4ad2b5e4e39200ce50ba169549603e222a82b83e63561a06.svg
200	http://taxonworks/assets/options-e0be240e424d0d4b06c90c9ee41fdf802815b6c10e1832d2d7b73730b5d66ddc.svg
200	http://taxonworks/packs/media/woff2/IBMPlexSans-Light-Latin1-dd97a1c4.woff2
200	http://taxonworks/packs/media/woff2/IBMPlexSans-Regular-Latin1-b7c1ebd6.woff2
200	http://taxonworks/assets/help-181272c7e9916b464ca8ddf5377ab6dd218d34f8581b70ea2428a4b5006a03e0.svg
200	http://taxonworks/packs/a372de3b0d958174db7e.worker.js
301	http://taxonworks/
200	http://taxonworks/signin
302	http://taxonworks/sessions
200	http://taxonworks/
301	http://taxonworks/
200	http://taxonworks/signin
302	http://taxonworks/sessions
200	http://taxonworks/



Finished in 29.93 seconds (files took 10.39 seconds to load)
3 examples, 0 failures

PONG <<< Here Redis is tested. Probably should add more descriptive output.
Stopping travis_test_1 ... done
Stopping tw_container  ... done
Stopping travis_db_1   ... done
Removing travis_test_1 ... done
Removing tw_container  ... done
Removing travis_db_1   ... done
Removing network travis_default
```

**Comment by mjy** [comment]
@LocoDelAssembly Does the configuration turn Redis on always, or by manual option?  I'm not sure if we have a use-case for it being on always (though maybe in the future to aid batch-loads, etc).

**Comment by LocoDelAssembly** [comment]
@mjy always. It was added as a service.

**Comment by mjy** [comment]
Will this open a security concern moving forward?

**Comment by LocoDelAssembly** [comment]
I think as long as the port is not exposed should be fine? Also this:
```
# By default Redis listens for connections from all the network interfaces
# available on the server. It is possible to listen to just one or multiple
# interfaces using the "bind" configuration directive, followed by one or
# more IP addresses.
#
# Examples:
#
# bind 192.168.1.100 10.0.0.1
bind 127.0.0.1
```

**Comment by mjy** [comment]
@LocoDelAssembly Keep issue open but merge this?

**Comment by LocoDelAssembly** [comment]
@mjy yes. Since I have plans to change the base image to customizable. If it is OK with you go ahead and merge. I re-ran the tests and now they pass: https://travis-ci.org/SpeciesFileGroup/taxonworks/jobs/592241727 (line 8441 is the Redis test)

**Pull request merged**
