### PR TITLE
Properly parse DwC scientificNameAuthorship field

### PR DESCRIPTION
**Pull request by LordFlashmeow**

### CODE REVIEW

**Comment by LocoDelAssembly** [comment]
@mjy this PR contains changes in lib/queries/taxon_name/autocomplete.rb that I'm not sure if can be accepted.

Additional data with production database:
```ruby
2.7.4 :012 > ap TaxonName.
where("cached_author_year ~ '[^()0-9]'").
where("cached_author_year ~ '\\d'").
where.not("cached_author_year ~ ',\s*\\d'").
map(&:cached_author_year)
[
    [  0] "Linnaeus (1754)",
    [  1] "(Wall.) (1831)",
    [  2] "(D. Don Florin & Boutelje) (1954)",
    [  3] "(Torrey Florin) (1956)",
    [  4] "Spach (1841)",
    [  5] "Greene (1882)",
    [  6] "(A. Murray Parlatore) (1864)",
    [  7] "Linnaeus (1753)",
    [  8] "Watson (1879)",
    [  9] "Miller (1768)",
    [ 10] "Hartweg (1847)",
    [ 11] "Linnaeus (1753)",
    [ 12] "Buchholz (1930)",
    [ 13] "Linnaeus (1753)",
    [ 14] "Linnaeus (1767)",
    [ 15] "L. (1753)",
    [ 16] "Sargent (1897)",
    [ 17] "(Bongard) Carrière (1855)",
    [ 18] "(Linnaeus Franco) (1949)",
    [ 19] "Linnaeus (1753)",
    [ 20] "(Plin. ex Tourn) Miller (1754)",
    [ 21] "Miller (1768)",
    [ 22] "Dougl. ex Forbes (1839)",
    [ 23] "(L.) Miller (1768)",
    [ 24] "A. Murray (1863)",
    [ 25] "Engelmann (1879)",
    [ 26] "(Gordon et Glendinning) Hildebrand (1861)",
    [ 27] "(Masters) Craib (1919)",
    [ 28] "(Pursh) Poiret (1817)",
    [ 29] "(Douglas ex D. Don) Lindley (1833)",
    [ 30] "Rehder (1939)",
    [ 31] "(Hooker) Nuttall (1849)",
    [ 32] "A. Murray (1863)",
    [ 33] "Rehder (1940)",
    [ 34] "Trew (1755)",
    [ 35] "Carrière (1866)",
    [ 36] "Masters (1903)",
    [ 37] "Miller (1754)",
    [ 38] "(DuRoi K. Koch) (1873)",
    [ 39] "Nuttall (1849)",
    [ 40] "A. Dietrich (1824)",
    [ 41] "(Linnaeus) Karsten (1881)",
    [ 42] "Masters (1906)",
    [ 43] "Parry ex Engelmann (1863)",
    [ 44] "(Moench) Voss (1907)",
    [ 45] "(Miller) Britton Sterns, & Poggenburg (1888)",
    [ 46] "Sargent (1898)",
    [ 47] "Engelmann (1863)",
    [ 48] "Engelmann (1862)",
    [ 49] "Franchet (1884)",
    [ 50] "Lemmon (1892)",
    [ 51] "Ehrenberg ex Schlechtendahl (1838)",
    [ 52] "Lambert (1803)",
    [ 53] "Morelet (1851)",
    [ 54] "Zuccarini (1832)",
    [ 55] "Douglas ex Loudon (1838)",
    [ 56] "D. Don (1836)",
    [ 57] "Lindley (1839)",
    [ 58] "Bailey & Hawksworth (1979)",
    [ 59] "Martinez (1943)",
    [ 60] "Miller (1768)",
    [ 61] "Engelmann (1848)",
    [ 62] "Engelmann (1880)",
    [ 63] "E. James (1823)",
    [ 64] "Walter (1788)",
    [ 65] "Engelmamm ex Parlatore (1868)",
    [ 66] "Balfour (1853)",
    [ 67] "Siebold and Zucc. (1842)",
    [ 68] "Douglas (1827)",
    [ 69] "Roezl ex Gordon (1862)",
    [ 70] "Schiede ex Schlechtendal et Chamisso (1831)",
    [ 71] "D.K. Baily (1987)",
    [ 72] "Robinson & Fernald (1894)",
    [ 73] "Lambert (1803)",
    [ 74] "Torrey et Frémont (1845)",
    [ 75] "Lambert (1832)",
    [ 76] "Douglas ex D. Don (1832)",
    [ 77] "D. Don (1836)",
    [ 78] "Swartz (1788)",
    [ 79] "Schiede ex Schlectendahl (1838)",
    [ 80] "Miller (1768)",
    [ 81] "Schiede ex Schlectendahl & Chamisso (1831)",
    [ 82] "Douglas ex Lawson & C. Lawson (1836)",
    [ 83] "Lambert (1805)",
    [ 84] "(Pallas) Regel (1858)",
    [ 85] "D. Don (1836)",
    [ 86] "Aiton (1789)",
    [ 87] "Miller (1768)",
    [ 88] "Sargent (1897)",
    [ 89] "Douglas ex D. Don (1832)",
    [ 90] "Engelmann (1848)",
    [ 91] "Linnaeus (1753)",
    [ 92] "Linnaeus (1753)",
    [ 93] "Carrière (1867)",
    [ 94] "Linnaeus (1753)",
    [ 95] "Miller (1768)",
    [ 96] "Franchet (1899)",
    [ 97] "Carrière (1867)",
    [ 98] "(Mirbel Franco) (1950)",
    [ 99] "Linnaeus (1753)",
    [100] "Nuttall (1849)",
    [101] "(L.) F.H.Wigg (1780)",
    [102] "Doweld (2001)",
    [103] "Jülich (1982)",
    [104] "Underw. (1899)",
    [105] "Gäum (1926)",
    [106] "P.Karst. (1881)",
    [107] "T.Macbr. (1922)",
    [108] "(Willem 1900)",
    [109] "Haller (1768)",
    [110] "Link (1833)",
    [111] "Kuntze (1891)",
    [112] "Presl (1836)",
    [113] "(Denis 1931)",
    [114] "Nannf. (1932)",
    [115] "(Berk.) Caval.-Sm. (1998)",
    [116] "Kunth (1837)",
    [117] "(Bonet 1947)",
    [118] "(Folsom 1896)",
    [119] "Linnaeus (1753)",
    [120] "(Reuter 1890)",
    [121] "(Mills 1934)",
    [122] "(Lubbock 1873)",
    [123] "(Maynard 1951)",
    [124] "(Say 1821)",
    [125] "(Folsom 1896)",
    [126] "(Fitch 1862)",
    [127] "(Tullberg 1871)",
    [128] "(Wray 1946)",
    [129] "(Osten Sacken 1877)",
    [130] "Weed, -1891",
    [131] "(Macquart 1850)",
    [132] "Zuccarini (1847)",
    [133] "J. F. Arnold (1785)",
    [134] "Linnaeus (1753)",
    [135] "(Banks 1907)",
    [136] "(Fr.) Fr. (1828)",
    [137] "L. 1753",
    [138] "Barnhart (1895)",
    [139] "(L.) Roxb. (1832)",
    [140] "Linnaeus (1753)",
    [141] "Linnaeus (1753)",
    [142] "Linnaeus (1753)",
    [143] "(Torr. & A. Gray) Scheele (1840)"
]
 => nil 
```

**Comment by LordFlashmeow** [comment]
That should make it behave like it did previously when unparsable

**Comment by LocoDelAssembly** [comment]
It is https://github.com/SpeciesFileGroup/taxonworks/pull/2456/files#diff-9bae240d4631e91e6a6a2ad2183d23c4a3edee15682a2f777082c955c1a4d9dbR380 which I'm unsure if it is good to go.

**Comment by LordFlashmeow** [comment]
So the problem is that the normalized value doesn't align with some nomenclatural codes, so it doesn't match up with some `cached_author_year` values. Maybe we revert to the way it was and add wildcards to `autocomplete_taxon_name_author_year_matches`?

**Comment by mjy** [comment]
Reminder- some cached values are bad dataand will be resolved by removing/fixed them during the updates that properly handle plant name handling.  I feel some of this optimization may be premature until we get that done.

**Comment by LocoDelAssembly** [comment]
I cherry-picked the first two commits that included new importer code, the rest of the commits are autocomplete ones.

**Comment by LordFlashmeow** [comment]
Closing until plant names are properly handled.

**Pull request closed without merging**
